#pragma once

#include <SDL.h>

/// @brief Defines the class responsible for managing user input
class InputManager
{
private:
	static Uint8* previousKeyboardState;
	static const Uint8* KEYBOARD_STATE;
	static int keyLength;

public:
	/// @brief Initialize the Input Manager Variables
	static void Initialize();
	
	/// @brief Clean up method during program termination
	static void Clean();

	/// @brief Receives all events generated by the user pressing the 
	/// keyboard and performs specific functionality based on this
	static void PollEvents();

	/// @brief Detects whether a specific key has been pressed
	/// @param key : The key to be checked
	/// @retval TRUE : Specified key has been pressed
	/// @retval FALSE : Specified key has not been pressed
	static inline bool GetKeyDown(SDL_Keycode key) { return !previousKeyboardState[key] && KEYBOARD_STATE[key]; }

private:
	InputManager();
};

