#pragma once

#include <SDL.h>

class InputManager
{
private:
	static Uint8* previousKeyboardState;
	static const Uint8* KEYBOARD_STATE;
	static int keyLength;

public:
	/// <summary>
	/// Initialize the Input Manager Variables
	/// </summary>
	static void Initialize();

	/// <summary>
	/// Clean up method during program termination
	/// </summary>
	static void Clean();

	/// <summary>
	/// Receives all events generated by the user pressing the keyboard
	/// and performs specific functionality based on this
	/// </summary>
	static void PollEvents();

	/// <summary>
	/// Detects whether a specific key has been pressed
	/// </summary>
	/// <param name="key">: The key to be checked</param>
	/// <returns>Returns true if the key was pressed</returns>
	static inline bool GetKeyDown(SDL_Keycode key) { return !previousKeyboardState[key] && KEYBOARD_STATE[key]; }

private:
	InputManager() {}
};

